---
- name: Build nodes in fixed-size batches
  hosts: localhost
  gather_facts: false
  vars:
    # Survey-friendly variables
    iterations: 1           # Number of batches to create (AAP Survey should set this)
    batch_size: 5           # Fixed: create 5 nodes per batch

    # Naming and pacing
    node_prefix: "node"
    start_number: 1
    max_node_number: 999
    delay_seconds: 30       # Delay between node creations inside a batch
    delay_between_batches: 60

    # Satellite settings (allow HG defaults to drive details)
    satellite_discovery_enabled: false
    org: "RedHat"
    location: "Denver"
    hostgroup: "Compute"
    compute_resource: ""
    compute_profile: ""
    domain: ""
    subnet: ""
    architecture: ""
    os: ""
    medium: ""
    pxe_loader: ""

  tasks:

  - name: Discover Satellite defaults (optional)
    include_tasks: tasks/discover_satellite_defaults.yml
    when: satellite_discovery_enabled | default(true) | bool

  - name: Prepare batch index sequence
    set_fact:
      batch_indices: "{{ range(1, (iterations | int) + 1) | list }}"

  - name: Create batches sequentially
    include_tasks: tasks/create_batch.yml
    loop: "{{ batch_indices }}"
    loop_control:
      loop_var: batch_index
      label: "Batch {{ batch_index }} of {{ iterations }}"
