---
- name: Provision RHEL 9 nodes with consecutive hostnames
  hosts: localhost
  gather_facts: false
  vars:
    node_prefix: "node"
    total_nodes: 5
    delay_seconds: 30
    # Align with Satellite Hostgroup 'Compute' (Id 2)
    org: "RedHat"
    location: "Denver"
    hostgroup: "Compute"
    # The following are intentionally left blank to let Hostgroup defaults apply
    compute_resource: ""
    compute_profile: ""
    domain: ""
    subnet: ""
    architecture: ""
    os: ""
    medium: ""
    pxe_loader: ""

  tasks:

  - name: Get existing node names from Satellite
    command: hammer host list --search "name ~ {{ node_prefix }}" --fields name --per-page 1000
    register: hammer_output

  - name: Extract used node numbers
    set_fact:
      used_nodes: "{{ hammer_output.stdout | regex_findall(node_prefix ~ '(\\d{3})') | map('int') | list }}"

  - name: Determine next available node names
    set_fact:
      available_nodes: >-
        {{
          range(1, 999)
          | reject('in', used_nodes)
          | map('int')
          | map('regex_replace', '^(\\d{1,3})$', lambda x: '%03d' | format(x | int))
          | map('regex_replace', '^', node_prefix)
          | list
          | slice(total_nodes)
        }}

  - name: Create nodes with delay
    include_tasks: tasks/create_node.yml
    loop: "{{ available_nodes }}"
    loop_control:
      loop_var: node_name
      label: "{{ node_name }}"
    when: available_nodes | length > 0

